### ISSUE TITLE
library name

### ISSUE THREAD

**Issue by Be-ing** [jcelerier/libremidi#19]
"RtMidi17" is a name that could become awkward in the future. What if the library ends up requiring C++20? Would you then rename it to RtMidi20? It may be a good idea to come up with an original name for this library.

**Comment by jcelerier** [comment]
That is a fairly good point, it started as just a few improvement to rtmidi thus the name, but has deviated by a whole lot now.
otoh I don't really want to break stuff for other contributors & users ... @cpyarger  @Cacodemon345  @yurkoy  what do you think ? 

If we're going for a new name what about something like cppmidi ? midipp ? remidi ? 

remidi doesn't deviate too much from rtmidi, contains the idea of a rework, and most importantly, libremidi makes a fun joke in french so it has my preference :p

**Comment by yurkoy** [comment]
I like the idea of the renaming in general and "remidi" as a successor name. I did a quick check and there exists however software with such name. I'm not sure about potential complications is we pick the same name.

**Comment by Cacodemon345** [comment]
rtmidi++

**Comment by Be-ing** [comment]
I like LibreMIDI. 

> otoh I don't really want to break stuff for other contributors & users

The cost of changing the name will only grow as more people use the library. Better to do it sooner than later.

**Comment by cpyarger** [comment]
I honestly don't have anything else I could contribute to this discussion. I'm good with any name. As a rose by any other name would smell as sweet.

**Comment by jcelerier** [comment]
alright, let's go for libremidi - I'll make a commit with the changes once all the current PRs are merged.

**Comment by Cacodemon345** [comment]
libremidi sounds like a really good name in my opinion.

**Comment by jcelerier** [comment]
it is done ! I will let a couple weeks for people to be bale to test and then make a release with the current state

**Comment by trolley813** [comment]
The new name is very good (in my opinion) because it can be parsed in 2 ways: Libre+MIDI (i.e. a free (libre) MIDI library) or lib+remidi (the Unix way of naming libraries as `libxxx` + re(worked) MIDI).

**Comment by keryell** [comment]
This makes me think to https://www.midilibre.fr/ also :-)
