### ISSUE TITLE
Reader doesn't read some standard MIDI files

### ISSUE THREAD

**Issue by jlidbeck** [jcelerier/libremidi#21]
reader.parse() fails to read MIDI from files with SYSEX meta events, throwing an exception that SYSEX is unsupported, though the error seems to indicate that it's incorrectly being parsed as a SYSEX channel event.

To reproduce, find a MIDI file with one or more SYSEX meta events (any on https://www.piano-e-competition.com/midi_2011.asp for example).

**Comment by jcelerier** [comment]
thanks, I think that we should look into adding those as a test corpus

**Comment by jcelerier** [comment]
with the fix in reader bugfixes I'm able to parse most of the files in https://colinraffel.com/projects/lmd/#get (the ones that don't also don't work in musescore and midiyodi so I'd err on the side of the files being broken, but if anyone knows of a better "midi file validation process"... :-) )

**Comment by jcelerier** [comment]
@ddiakopoulos you may be interested in that fix :)

**Comment by jlidbeck** [comment]
I have a few more fixes, but they are less critical--dealing with extra bytes allocated to store messages, and filled with zeros or 0xFF. Probably not as critical, but sizing the vectors more tightly would help with porting them to the writer, so I've made a separate issue for that more general task.

**Comment by jcelerier** [comment]
I've worked a bit on the reader to improve its compatibility - and added more precise error checking (and reporting).
Now it will report 4 possible cases: 
- it could not parse the data at all
- it could parse the data partially (e.g. some events / tracks could not be parsed)
- it could parse the data entirely 
- it could parse the data entirely and perform some additional checks to ensure that it conforms with SMF rules.


I also added checks before reading bytes to make sure that we do not read out-of-bounds in the case of invalid MIDI files (e.g. runaway events...) - almost none of that used to be checked so invalid midi files would have crashed (at best).

**Comment by jcelerier** [comment]
Also I added a test corpus that I found (and tested with address sanitizer on an additional corpus of a few thousand files).

**Comment by jcelerier** [comment]
Just tested with a much larger corpus (169k files) and it does not seem to have any kind of memory errors with ASAN: https://archive.org/details/themagicofmidiv1 so I'd guess it's reasonably safe ! :)

**Comment by jcelerier** [comment]
in total:

    assertions: 299248 | 296049 passed | 3199 failed
 
the failed assertions are *mostly* invalid midi files for which there is no check that is going to mark them as invalid (but they do parse)

**Comment by jcelerier** [comment]
closing this - please reopen other issues if you see files that still don't parse :-) thanks !
