### ISSUE TITLE
Synchronize reader and writer classes to work together better

### ISSUE THREAD

**Issue by jlidbeck** [jcelerier/libremidi#25]
Reader and writer have slightly different internal serialization formats, and so MIDI cannot be transferred from one data structure to the other except one event at a time. 

Because the formats are very similar, they could be correlated, so e.g. a writer could be constructed from the reader via a straightforward vector copy.

The I/O methods could be standardized as well--the reader currently parses a byte vector, while the writer writes an ostream.

**Comment by jcelerier** [comment]
Did some work related to this here : https://github.com/jcelerier/libremidi/pull/47 

Basically, the writer can just be a much simpler struct where one can set the vector of midi tracks however one sees fit.

**Comment by jcelerier** [comment]
I've merged the related issue, please reopen issues if you see improvements to the api ! thanks :)
