### ISSUE TITLE
MacOS Randomly crashing 

### ISSUE THREAD

**Issue by cpyarger** [jcelerier/libremidi#37]
I keep getting reports of crashes on MacOS,  The crash reports state:

```terminating with uncaught exception of type rtmidi::driver_error: MidiInCore::initialize: error creating OS-X MIDI client object (-50).```

I have not yet been able to replicate it personally. Windows and Linux have been rock solid.

**Comment by jcelerier** [comment]
hm thanks, never had that issue on macos... do you think you could put a breakpoint on when the exception gets thrown ? 
(`catch throw` in gdb or `break set -E C++` in lldb)

**Comment by cpyarger** [comment]
I haven't had the issue personally. nor been able to replicate it, just reporting it in. as I have had a few messages about it.

**Comment by cpyarger** [comment]
I through in an error callback and it took care of it sorta, Apparently it's not breaking anything, as I haven't gotten any complaints yet
