### ISSUE TITLE
Updated to the latest master and now crashing 

### ISSUE THREAD

**Issue by cpyarger** [jcelerier/libremidi#38]
on closing ports when shutting down the application
![image](https://user-images.githubusercontent.com/1778298/110582037-905c0200-8139-11eb-9c26-842a4e508725.png)

**Comment by cpyarger** [comment]
It does not happen if i decide not to close the ports prior to close

**Comment by jcelerier** [comment]
hummm, weird, do you think you could do a git bisect to find the offending commit ?

**Comment by jcelerier** [comment]
can you pull and check again ? I think I know what caused this, that was a stupid mistake

**Comment by jcelerier** [comment]
closing this, please reopen if you see the issue again but I think it's gone ! :-)
