### ISSUE TITLE
plans for pipewire?

### ISSUE THREAD

**Issue by cpyarger** [jcelerier/libremidi#44]
Are we planning on integrating pipe wires MIDI backend?

**Comment by jcelerier** [comment]
That would make a lot of sense, do you know relevant docs on this ?

**Comment by jcelerier** [comment]
I tried buildling the MIDI pipewire example but it does not build yet here... certainly it'll be good in a few months :)

**Comment by dromer** [comment]
Doesn't pipewire just use the alsa sequencer API?
Not sure what would be the advantage of a pipewire specific implementation other than more technical debt :shrug:

**Comment by dromer** [comment]
What do you mean with "one client for the midi part, one client for the audio part"?

Qtractor under pipewire, using jack for audio and alsa for midi:

![](https://i.imgur.com/OVQ691U.png)

**Comment by jcelerier** [comment]
yes ahah. how does that work in the first graph if you launch the same app twice ??

**Comment by dromer** [comment]
Haha, yup you got me there. Raysession then groups all the midi ports into one of the blocks -_-

![](https://i.imgur.com/Jv7wovW.png)

**Comment by jcelerier** [comment]
:'D

nevertheless, it's definitely not critical but if someone can implement such a back-end I'd happily look into it, especially if it allows reusing an existing pw_context / pw_main_loop like the other backends now allow

**Comment by tsankuanglee** [comment]
Another benefit I'd add by supporting pipewire is the ability to use bluetooth MIDI devices.

**Comment by jcelerier** [comment]
@dromer could you confirm this with an actual midi BLE device? I thought that since bluez 5 BLE-MIDI had to go through another daemon and wasn't exposing audio / midi devices directly to alsa

**Comment by jcelerier** [comment]
hmmm maybe there's something to simulate one with an android app ? or something I could flash on an ESP32

**Comment by dromer** [comment]
It would be strange if pipewire wouldn't expose such midi ports to all other midi software/devices.

**Comment by jcelerier** [comment]
see e.g. https://github.com/arkq/bluez-alsa

**Comment by tsankuanglee** [comment]
I'm using pipewire with a bluetooth midi device and a few other wired ones here. I can see all midi devices in [qpwgraph](https://github.com/rncbc/qpwgraph), and am able to patch them freely with other apps.

`amidi -l` shows the wired devices, but not the bluetooth one.

I'm assuming this is because of pipewire's support for [bluetooth MIDI](https://github.com/PipeWire/pipewire/blob/84699032be0a6a8a5e0174c5ca09c1cdc7ae2148/NEWS#L1562), but I may be wrong in that some other utility is exposing it as a wired one instead.

**Comment by jcelerier** [comment]
okay, got nerd-sniped by this, I started some work on it yesterday, there should be results soon :)

**Comment by jcelerier** [comment]
https://github.com/jcelerier/libremidi/assets/2772730/682771b4-954d-4c97-8dd6-253161df69bc

getting there...

**Comment by jcelerier** [comment]
okay, current master has basic support for input and output (virtual ports only). 

TODO:
- [ ] observer and port enumeration support
- [ ] auto-connect to the relevant port
- [ ] support using an existing pipewire runloop and / or filter
- [ ] test-drive it :)

**Comment by jcelerier** [comment]
some more progress and bugfix, now it should support hotpug events.
please note that the pipewire API is somewhat involved and intricate - I'd really really like others to test-drive and torture it as i'm pretty sure there's a heavy amount of corner cases that may still fail spectacularly.

**Comment by tsankuanglee** [comment]
@jcelerier OK, I'll give it a try with my bluetooth midi device and report back. May take a while though.

**Comment by tsankuanglee** [comment]
Not an expert in c++, here's what I got:

```
$ g++ -I./include/ -I/usr/include/pipewire-0.3/ -I/usr/include/spa-0.2/ -I_deps/readerwriterqueue-src/ -lliblibremidi examples/backends/midi1_in_pipewire.cpp -o midi1_in_pipewire

...omit...

./include/libremidi/backends/pipewire/helpers.hpp:101:23: error: ‘class libremidi::observer_pipewire’ has no member named ‘process’
  101 |                  self.process(position);
      |                  ~~~~~^~~~~~~
```

**Comment by jcelerier** [comment]
weird, builds fine here. I added it to the CI to see where things go wrong.

**Comment by jcelerier** [comment]
![damn](https://github.com/jcelerier/libremidi/assets/2772730/6f586e27-f929-4679-8d07-252c96930fe7)

well this build matrix is certainly putting sadness in my soul

**Comment by jcelerier** [comment]
okay those were minor issues - CI is now green with pipewire across three debian versions so I'd say the error is most likely somewhere else..

**Comment by tsankuanglee** [comment]
I ended up just using `LIBREMIDI_EXAMPLES` for building examples, rather than compiling it manually. The result: it worked and my bluetooth MIDI device is shown in `midi1_in_pipewire`'s output!

Thanks so much!!

**Comment by jcelerier** [comment]
et voilà :) 

https://github.com/jcelerier/libremidi/assets/2772730/9f39a950-9593-44c3-b354-cfaa00fdd167

**Comment by jcelerier** [comment]
it's where i want it to be at df33d0abacd8a5cf8b64ea93c0d397dea2d6b55f ; again i'm pretty sure there could be subtle concurrency issues, but I test-drived it with fsanitize=address fsanitize=undefined fsanitize=thread until it came out clean
