### ISSUE TITLE
get_message_type strange behaviour?

### ISSUE THREAD

**Issue by melMass** [jcelerier/libremidi#46]
Hi,

I'm trying to use a switch on get_message_type() inside the midin_in callback but for some reason it's not handling every cases. Here is a small repro, this is not working:

```c
const auto chan = mess.get_channel();
int32_t b1, b2, b3;
b1 = (int32_t) mess.bytes[1];
b2 = (int32_t) mess.bytes[2];
b3 = (int32_t) mess.bytes[3];

switch(mess.get_message_type()){
        case libremidi::message_type::POLY_PRESSURE:
                console->AddLog("# Channel (%u) | POLY_PRESSURE: %u - %u", chan, b1, b2);
            break;
}

```

This does work, but only when receiving on channel 1

```c
const auto chan = mess.get_channel();
auto msg = (libremidi::message_type) mess.bytes[0];
int32_t b1, b2, b3;
b1 = (int32_t) mess.bytes[1];
b2 = (int32_t) mess.bytes[2];
b3 = (int32_t) mess.bytes[3];
switch (msg) {

        case libremidi::message_type::POLY_PRESSURE:
                console->AddLog("# Channel (%u) | POLY_PRESSURE: %u - %u", chan, b1, b2);
            break;

}
```

**Comment by jcelerier** [comment]
hm on which platform are you ? I just tried with my keyboard and it seems to work fine (I'm under Linux).

**Comment by melMass** [comment]
Sorry, using macOs 10.14 with the OSX Core Midi backend

Here is a screen of the app I'm working on, in the log as you can see I'm sending the same note:

- first on channel 1, works
- then on channel 2:  I'm receiving 145 for NOTE_ON and 129 for NOTE_OFF
- then on channel 3:  I'm receiving 146 for NOTE_ON and 130 for NOTE_OFF
- then on channel 4:  I'm receiving 147 for NOTE_ON and 131 for NOTE_OFF

![image](https://user-images.githubusercontent.com/7041726/114386728-e46f6180-9b91-11eb-9c3e-1427751c1494.png)

**Comment by melMass** [comment]
Sorry, it's not very useful. I'm going to try a bit harder before reformulating the issue, can you explain what's going on in:
```c++
  message_type get_message_type() const
  {
    if (bytes[0] >= uint8_t(message_type::SYSTEM_EXCLUSIVE))
    {
      return (message_type)(bytes[0] & 0xFF);
    }
    else
    {
      return (message_type)(bytes[0] & 0xF0);
    }
}
```

What is `& 0xF0` for? The issue seems to be related

**Comment by jcelerier** [comment]
just in case - I think that you shouldn't access 

    b3 = (int32_t) mess.bytes[3];

as most likely there's no data here so you're reading random memory (bad bad bad).

otherwise, I am at loss: I tried the following code on a mac and I also get the expected output:

```
{
  libremidi::midi_in midi{libremidi::API::MACOSX_CORE, "libremidi-test"};

  midi.open_port(2);
  while(true)
  {
    libremidi::message mess = midi.get_message();
    if(!mess.bytes.empty())
    {
      const auto chan = mess.get_channel();
      int32_t b1, b2, b3;
      b1 = (int32_t) mess.bytes[1];
      b2 = (int32_t) mess.bytes[2];

      switch(mess.get_message_type()){
        case libremidi::message_type::POLY_PRESSURE:
          fprintf(stderr, "# Channel (%u) | POLY_PRESSURE: %u - %u\n", chan, b1, b2);
          fflush(stderr);
          break;
      }
    }
  }
}
```

**Comment by melMass** [comment]
> just in case - I think that you shouldn't access
>  ...

Yes, that was it! Not accessing this fourth byte made `get_message_type` behave as expected!

So there are never any relevant pieces of information in `mess.bytes[3]` ?

Thanks

**Comment by melMass** [comment]
On a similar note `mess.timestamp` always returns 0. Is it possible that if I access it multiple times it mess things up? Sorry for all the questions...

**Comment by jcelerier** [comment]
> So there are never any relevant pieces of information in mess.bytes[3] ?

it depends on your midi messages.
The vast majority of "usual" messages have 2 (program change, channel pressure) or 3 (note on, note off, control change) bytes. But for instance sysex messages can have arbitrarily high number of bytes - but most common MIDI use cases don't involve sysex.

**Comment by jcelerier** [comment]
> On a similar note mess.timestamp always returns 0. Is it possible that if I access it multiple times it mess things up? Sorry for all the questions...

weird too, it also works fine here on my mac.

One thing you could do is to compile your program with -fsanitize=address -fsanitize=undefined as this will catch a lot of errors

**Comment by melMass** [comment]
> One thing you could do is to compile your program with -fsanitize=address -fsanitize=undefined as this will catch a lot of errors

I had no idea about those flags, this is very very useful thanks!

**Comment by melMass** [comment]
Closing now I'll reopen it if needed.
