### ISSUE TITLE
Faulty MIDI clock-in messages with ALSA support?

### ISSUE THREAD

**Issue by Stmpf** [jcelerier/libremidi#59]
Hi @jcelerier,

thank you very much for this great library!

I'm heaving trouble getting correct clock in messages on ALSA using different platforms (RPi3B+, MBP), distributions (RPi OS, Ubuntu22.04) and MIDI devices.

When using your test _cmidiin.cpp_, I get the correct message content on Windows...
```
Byte 0 = 248, stamp = 0.063
Byte 0 = 248, stamp = 0.062
....
```
... but I get the following with ALSA support:
```
Byte 0 = 248, Byte 1 = 248, stamp = 0
Byte 0 = 248, Byte 1 = 248, stamp = 0
....
```
Instead of 24 pulses per quarter, only approx. 12 messages (with two bytes content) arrive.

Am I doing something wrong?

Thanks!

**Comment by jcelerier** [comment]
hello ! are you using the alsa sequencer or raw backend ?

**Comment by Stmpf** [comment]
I wasn't aware of the alsa sequencer so I guess I'm using raw backend. Hardware MIDI device is plugged in directly to USB. It looks like I do receive MIDI note messages correctly.

This is my CMakeLists.txt for the example running on Ubuntu: 

    cmake_minimum_required(VERSION 3.13)
    
    project(exampleProject)

    set(CMAKE_CXX_STANDARD 17)
    set(LIBREMIDI_HEADER_ONLY ON)
	set(LIBREMIDI_EXAMPLES ON)
	set(LIBREMIDI_ALSA ON)
	
	add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/libremidi)
	add_executable(example src/main.cpp)
	target_link_libraries(example libremidi)

cmake Output:

    -- Found ALSA: /usr/lib/aarch64-linux-gnu/libasound.so (found version "1.2.6.1") 
	
I have installed alsa-tools via apt:

    Package: alsa-tools
    Version: 1.2.5-2

**Comment by Stmpf** [comment]
Hi! Did you have a chance to have a look at the issue? Or could you guide me into a direction on how to debug my problem?

Thanks!

**Comment by Stmpf** [comment]
Ok, I debugged the problem and think that clock messages are simply not yet supported for raw alsa. I'm not able to push into a dev branch to create a pull request so here is the fix that works for me:

``` diff
--- a/include/libremidi/detail/raw_alsa.hpp
+++ b/include/libremidi/detail/raw_alsa.hpp
@@ -61,6 +61,15 @@ struct midi_stream_decoder
       // TODO special message
       return sz;
     }
+    else if(((uint8_t)bytes[0] & 0xF8 ) == 0xF8)
+    {
+      // Clock messages
+      msg.bytes.reserve( 1 );
+      msg.bytes.push_back( *bytes++ );
+      runningStatusType_ = msg.bytes[0];
+
+      return 1;
+    }
     else
     {
       if (sz <= 1)
```

**Comment by jcelerier** [comment]
hello, sorry I'm super busy with my job right now, hadn't had enough time to look at this. 
If you want you can just fork the repo and push your patch there, this way the commit will be properly attributed to you :)

     1. hit the fork button
     2. git clone https://github.com/Stmpf/libremidi
     3. do the patch, commit, push
     4. go to https://github.com/Stmpf/libremidi and it should show a "create pull request" button

**Comment by jcelerier** [comment]
(in any case the patch looks correct)

**Comment by Stmpf** [comment]
> hello, sorry I'm super busy with my job right now...

No problem! Thanks for the time already invested in the lib :)
