### ISSUE TITLE
Integral timestamps/deltas

### ISSUE THREAD

**Issue by ejconlon** [jcelerier/libremidi#68]
This looks like a nice revamp of RtMidi, thanks! One thing that bugs me as I maintain the Haskell bindings to RtMidi is that event times are represented as doubles. No other music protocol at that level uses floating point - not midi files, and not OSC! I think some of the backends even have integral timestamps. Are you open to changing this (or getting contributions along those lines)?

**Comment by jcelerier** [comment]
hi! yes, it's a pretty bad decision. I'm thinking of tagging the current branch as it is, and starting a v4 branch which would have deep API changes and fix long-standing API issues such as this and some other ones

**Comment by jcelerier** [comment]
it's done in branch v4

**Comment by ejconlon** [comment]
That's great! It will take me a little while to test it out (looking to try out fficxx for generated Haskell-C++ bindings) but I look forward to using it!

**Comment by jcelerier** [comment]
i'm almost done with the complete overhauling of timestamps.. now it should be nano seconds everywhere, plus you'll have the choice between relative timestamps, absolute (as given by the host api with an "unknown" reference frame), and absolute as per the system's monotonic clock :)

**Comment by jcelerier** [comment]
done in all the backends in branch v4
