### ISSUE TITLE
2 tests fail

### ISSUE THREAD

**Issue by yurivict** [jcelerier/libremidi#72]
[log](https://people.freebsd.org/~yuri/libremidi-3.0-tests.log)

Version: 3.0
clang-15
FreeBSD 13.2

**Comment by jcelerier** [comment]
working on them.. I could fix the invalid midi parsing ones: https://github.com/jcelerier/libremidi/tree/v3

**Comment by jcelerier** [comment]
can you try this branch? https://github.com/jcelerier/libremidi/tree/v4

and... do you know any way I could put freebsd CI in github actions?

**Comment by yurivict** [comment]
> can you try this branch [...]

I will try this branch a bit later.

> and... do you know any way I could put freebsd CI in github actions?

Does [this](https://github.com/marketplace/actions/freebsd-vm) answer your question?

**Comment by yurivict** [comment]
> can you try this branch [...]

configure fails:
```
-- libremidi: Using std::vector for libremidi::message
-- libremidi: using ALSA
-- libremidi: using linked JACK
-- libremidi: compiling tests
CMake Error at CMakeLists.txt:360 (include):
  include could not find requested file:

    Catch


CMake Error at CMakeLists.txt:361 (catch_discover_tests):
  Unknown CMake command "catch_discover_tests".
```

**Comment by jcelerier** [comment]
I'm trying to add the VM, do you know how can I install boost and jack with pkg? https://github.com/jcelerier/libremidi/blob/v4/.github/workflows/build_cmake.yml#L127

otherwise I think the tests should be good

**Comment by yurivict** [comment]
> [...] do you know how can I install boost and jack with pkg? [...]

```
$ sudo pkg install jackit boost-libs
```

This command searches for packages by name:
```
$ pkg search {name}
```

**Comment by jcelerier** [comment]
almost there... https://github.com/jcelerier/libremidi/actions/runs/5649349837/job/15303504636

**Comment by yurivict** [comment]
```#!/bin/bash``` should be ```#/usr/bin/env bash```.

**Comment by jcelerier** [comment]
everything is green in CI :) https://github.com/jcelerier/libremidi/actions/runs/5649457339
