### ISSUE TITLE
How to open port?

### ISSUE THREAD

**Issue by ktulhu2000** [jcelerier/libremidi#78]
Hi! 
Im kinda writing driver between midi controller and synth.
So there is a need of opening specific devices to communicate. There is an open_port, right? 
Seems it gets abstract meaningless index. Especially during plug outs.

I see changelog says now ports can be open with (device) handler, but didn't find any trace in examples.
Or may be I missed something.
Thanks

**Comment by jcelerier** [comment]
Hello! 
You can check for instance this example: https://github.com/jcelerier/libremidi/blob/master/examples/echo.cpp

Normally the index API is entirely gone, I'll have to update the docs

**Comment by jcelerier** [comment]
docs updated: https://github.com/jcelerier/libremidi/blob/master/docs/usage.md
