### ISSUE TITLE
Message Queue Limit Reached

### ISSUE THREAD

**Issue by brunorzn** [jcelerier/libremidi#79]
Hi,

I need to fetch many MIDI messages at the same time. 

I got the message: "midi_in: message queue limit reached!!"

How to bypass this ?

This is critical for my application: I'm building a MIDI controller and many midi messages are sent on the same time from the host to the controller to init the correct values.

Thanks,

Bruno

**Comment by jcelerier** [comment]
hi! how did you manage to solve this?

**Comment by brunorzn** [comment]
Hi, 

I gave up and went back to rtMidi... Sorry
