### ISSUE TITLE
Add a license file for the project as a whole

### ISSUE THREAD

**Issue by marinedalek** [jcelerier/libremidi#82]
I'm working on adding libremidi port to vcpkg, and it requires a software license file. I see separate licenses that cover RTMidi and ModernMidi, but there doesn't appear to be one for libremidi itself. 

In addition to being added to the current head of the repo, if possible a version of tag v3.0 with the license would also be needed, as that is the latest release and thus what would be installed by default in vcpkg.

**Comment by jcelerier** [comment]
added and tagged :)
