### ISSUE TITLE
[regression in 4.0] Build fails: fatal error: 'sys/timerfd.h' file not found

### ISSUE THREAD

**Issue by yurivict** [jcelerier/libremidi#83]
```
In file included from /usr/ports/audio/libremidi/work/libremidi-4.0/include/libremidi/client.cpp:4:
In file included from /usr/ports/audio/libremidi/work/libremidi-4.0/include/libremidi/backends.hpp:15:
In file included from /usr/ports/audio/libremidi/work/libremidi-4.0/include/libremidi/backends/alsa_seq.hpp:15:
In file included from /usr/ports/audio/libremidi/work/libremidi-4.0/include/libremidi/backends/alsa_seq/midi_in.hpp:4:
/usr/ports/audio/libremidi/work/libremidi-4.0/include/libremidi/backends/linux/helpers.hpp:3:10: fatal error: 'sys/timerfd.h' file not found
#include <sys/timerfd.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

FreeBSD 13.2

**Comment by jcelerier** [comment]
hmmm this is very linux-specific code (it's only used for ALSA backend), I don't know why it would even go through this in freebsd..

**Comment by jcelerier** [comment]
is there a timerfd alternative there?

**Comment by yurivict** [comment]
FYI: ALSA is supported on FreeBSD.

But libremidi now uses linusixms like ```timerfd``` in the ALSA code so I had to disable ALSA in the FreeBSD port.

**Comment by jcelerier** [comment]
> FYI: ALSA is supported on FreeBSD.

oh, okay I did not know (or expect this) at all. And there isn't any timerfd shim for BSD?

**Comment by jcelerier** [comment]
I disabled it for now if timerfd is not available. Instead I'd like to consider using the native BSD MIDI APIs, I read about /dev/umidi and OSS but could not find much docs...

**Comment by jcelerier** [comment]
should be good on 4.1.0, please reopen if you still encounter issues!
