### ISSUE TITLE
Add repology badge to README.md

### ISSUE THREAD

**Issue by luzpaz** [jcelerier/libremidi#96]
Track downstream package versions of libremidi. Keep the ecosystem up to date. 

### Large badge

[![Packaging status](https://repology.org/badge/vertical-allrepos/libremidi.svg?columns=3&header=libremidi)](https://repology.org/project/libremidi/versions)

### Small badge

[![Packaging status](https://repology.org/badge/tiny-repos/libremidi.svg)](https://repology.org/project/libremidi/versions)

**Comment by jcelerier** [comment]
done thanks !
